# Generated by Django 4.2.7 on 2023-12-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=225)),
                ('DESCRIPTION', models.TextField(max_length=500, null=True)),
                ('PRICE', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('imagepath', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
