# Generated by Django 5.0 on 2023-12-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_imagepath_productmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='PRODUCT CATEGORY',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='IMAGE',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
