# Generated by Django 5.0 on 2023-12-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmodel_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='PRODUCT CATEGORY',
            field=models.TextField(null=True),
        ),
    ]
