# Generated by Django 5.0 on 2023-12-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='PRODUCT CATEGORY',
            new_name='PRODUCT_CATEGORY',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='RATINGS',
            field=models.IntegerField(default=0),
        ),
    ]
