# Generated by Django 5.0 on 2023-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_product_category_productmodel_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='PRODUCT_CATEGORY',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
